spring:
  profiles:
    active: default
    include: local
  datasource:
    url: jdbc:mysql://localhost:3306/r123513412?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration/schema
#    locations: classpath:db/migration
    clean-on-validation-error: true
  jackson:
    serialization:
      write-dates-as-timestamps: true

server:
  port: 0

logging:
  level:
    org: ERROR
    com: ERROR
    com.example.demo: TRACE
